### PR TITLE
Set psalm level to one

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

### CODE REVIEW

**Review by roxblnfk — COMMENTED** [review]
I think psalm level 2 is ok. Level 1 requires more work resources

**Comment by vjik** [comment]
> I think psalm level 2 is ok. Level 1 requires more work resources

Very often highest pslam level help found problems and bugs in code.

**Comment by roxblnfk** [comment]
> Very often highest pslam level help found problems and bugs in code.

level 2 is enough for that

**Comment by samdark** [comment]
Level 2 is alright for the start. Could be lowered but that's optional.

**Pull request closed without merging**
